name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  validate-html:
    name: Validar HTML
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v3

      - name: Validar HTML
        uses: Cyb3r-Jak3/html5-validator-action@v1
        with:
          file: index.html  # Asegúrate de que este sea el archivo correcto

  deploy:
    name: Desplegar Sitio
    runs-on: ubuntu-latest
    needs: validate-html  # Espera a que la validación termine antes de desplegar

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v3

      - name: Publicar en GitHub Pages
        uses: actions/upload-pages-artifact@v1

      - name: Desplegar
        uses: actions/deploy-pages@v1
